// <auto-generated />
namespace WebApplicationWeek3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ClubModeladded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ClubModeladded));
        
        string IMigrationMetadata.Id
        {
            get { return "201810051048552_Club Model added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
